<?php
    $url_path = "options-general.php?page=". ConnatixPlugin::$PLUGIN_FILE . "&ad_id=";
    $home_path = "options-general.php?page=". ConnatixPlugin::$PLUGIN_FILE;
    $form_url = ($ad_id != null && $ad_id != -1) ? $url_path . $ad_id : $home_path;
?>
<!--The page-->
<div class="wrap connatix-wrap">
    <div class="connatix-preloader">
        <img src="<?php echo CONNATIX_PLUGIN_URL . "img/loader.gif"; ?>" alt="loader" />
    </div>

    <?php
        require_once plugin_dir_path(__FILE__) . "connatix.menu.phtml"; 
    ?>
    <?php
        if($ad_id != null && $ad_id == -1)
        {
           echo "<b>*** Note: Add a new Ad Unit or pick an already created one from the right toolbox!</b>";
        }
    ?>
    <!-- Beginning of the Plugin Form -->
    <form method="post" action="<?php echo $form_url ?>" id="form1">
        <?php if($ad_id != -1) { ?>
        <input type="hidden" name="id" value="<?php echo $ad_id ?>" />
        <?php } ?>
        <input type="hidden" name="action" value="<?php echo ConnatixJSPlugin::$POST_ACTION ?>" />
        <div id="heads-toolbox" class="connatix-toolbox" id="connatix-toolbox">
            <a class="connatix-add-new" href="<?php echo $home_path ?>"><h3>Add New<span>+</span></h3></a>
            <ul>
                <?php
                    foreach($ads as $ad)
                    {
                        $u = $url_path . $ad->_id;
                        $selected = $ad == $ad_unit ? "class='selected'" : "";
                        $name = (isset($ad->_name)) ? $ad->_name : "No Name";
                    
                        echo "<a href='$u'><li $selected>$name</li></a>";
                    }
                ?>
            </ul>
        </div>
        <!-- General settings section with it's fields and notes -->
        <div id="postlist">
            <div id="heads-up" class="postbox ">
                <h3><span>GENERAL SETTINGS</span></h3>
                <div class="inside">
                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>AD Unit Name:</b></td>
                            <td><input title="The ad unit name." type="text" maxlength="100" name="name" value="<?php echo $ad_unit->_name; ?>" /></td>
                        </tr>
                        <tr>
                            <td class="connatix_head"><b>PUBLIC TOKEN:</b></td>
                            <td><input title="The public token provided." type="text" maxlength="100" name="token" value="<?php echo $ad_unit->_token; ?>" /></td>
                        </tr>
                    </table>
                </div>
            </div>
            <!-- Listing ad unit section with it's fields and notes -->
            <div id="heads-up" class="postbox ad-unit">
                <h3><span>TARGETING</span></h3>
                <div class="inside">
                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>Page</b></td>
                            <td>
                                <select title="The category page you want to install the Ad." name="categoryID[]" class="connatix-page-selector" multiple="multiple" size="6">
                                    <?php
                                        
                                        $cat_url = get_home_url();
                                        
                                        $sel = in_array(0, $ad_unit->_categoryID) ? "selected='selected'" : "";
                                        
                                        echo "<option value='0' data-link='$cat_url' $sel>Homepage</option>";
                                        
                                        $sel = in_array(-1, $ad_unit->_categoryID) ? "selected='selected'" : "";
                                        
                                        echo "<option value='-1' data-link='javascript:void(0)' $sel>All Post Pages</option>";
                                        
                                        foreach($categories as $category)
                                        {
                                            $category_url = get_category_link($category->cat_ID);
                                            $selected = "";
                                            if(in_array($category->cat_ID,$ad_unit->_categoryID))
                                            {
                                                $selected = "selected='selected'";
                                                $cat_url = $category_url;
                                            }
                                        
                                            echo "<option data-link='$category_url' $selected value='".$category->cat_ID."'>".$category->name."</option>";
                                        }
                                    ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <?php
                                $selected = ($ad_unit->_skip_adunit) ? "checked='checked'" : "";
                            ?>
                            <td colspan="3" style="line-height:8px">
                                <span class="description"><input data-ignore="true" title="Check this only if you use the Connatix Widget." type="checkbox" value="1" name="skip_adunit" <?php echo $selected ?> /> <b title="Check this only if you use the connatix widget">* Widget Only</b></span>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <!--Destination page setup section with it's fields and notes-->
            <div id="heads-up" class="postbox ">
                <h3><span>DESTINATION PAGE SETUP</span></h3>
                <div class="inside">
                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>PERMANENT LINK:</b></td>
                            <td class="connatix_in"><?php echo get_site_url() . "/"; ?>
                            </td>
                            <td>
                                <input type="text" name="dest" placeholder="promoted" title="Custom destination page permalink." maxlength="20" value="<?php echo $ad_unit->_dest ?>" />
                            </td>
                        </tr>
                        <tr>
                             <td class="connatix_head"><b>Custom CODE:</b></td>
                             <td colspan="2"><textarea rows="5" title="This code will be added in the HTML of the destination page." name="destcode"><?php echo $ad_unit->_dest_code; ?></textarea>
                             <span class="description">*Note: The custom code will affect the chosen page. Even though you save the code from a different Ad Unit, if that Ad Unit is targeting the "/promoted" page, the destination page custom code will be the last one saved, regardless of the Ad Unit. </span>
                             </td>
                        </tr>
                        <tr>
                            <td colspan="3"><span style="color:green;"><b>Current permalink: &nbsp;</b><?php echo get_site_url()."/".$ad_unit->_dest ?></span></td>
                        </tr>
                        
                    </table>
                </div>
            </div>
        </div>
        <div class="clear"></div>
        <!--Submit form button-->
        <input type="submit" name="delete" class="button-primary connatix-ad-delete" value="Delete ad" />
        <input type="submit" class="button-primary" value="Save Changes" />

    </form>
    <!--Footer-->
    <hr class="connatix-break"/>

    <div class="logo"></div>
</div>
<script>
    var CONNATIX_PARTNER_API = "<?php echo CONNATIX_PARTNER_API; ?>?token=";
</script>