<!--The page-->
<div class="wrap connatix-wrap">
    <div class='connatix-preloader'>
          <img src="<?php echo CONNATIX_PLUGIN_URL . "img/loader.gif"; ?>"/> 
    </div>
    
    <?php
        require_once plugin_dir_path(__FILE__) . "connatix.menu.phtml"; 
    ?>
    
    <!-- Beginning of the Plugin Options Form 1 -->
    <form method="post" action="options-general.php?page=<?php echo ConnatixPlugin::$PLUGIN_FILE ?>&connatix_product=inpost" id="form1">
        <input type='hidden' name='action' value='<?php echo ConnatixInpostPlugin::$POST_ACTION ?>'/>
        <!--General settings section with it's fields and notes-->
        <div id="postlist"><div id="heads-up" class="postbox ">
                <h3><span>GENERAL SETTINGS</span></h3>
                <div class="inside">
                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>PUBLIC TOKEN:</b></td>
                            <td>
                                <abbr title="The public token provided.">
                                <input type="text" maxlength="100" name="token" value="<?php echo $options->_token; ?>" /></abbr></td>
                        </tr>
                        <tr>
                            <td colspan="2"> <span class="description">* Insert the public token provided, here.</span></td>
                        </tr>
                    </table></div></div>

            <!--Listing ad unit section with it's fields and notes-->
            <div id="heads-up" class="postbox ad-unit">
                <h3><span>INPOST AD UNIT</span></h3>
                <div class="inside">

                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>Insert your InPost:</b></td>
                            <td><abbr title="Insert">
                                    <select data-ignore='true' name='type'>
                                        <?php
                                            $selected = ($options->_type == 0) ? "selected='selected'" : ""; 
                                        ?>
                                        <option value='0' <?php echo $selected ?>>In custom location</option>
                                        <?php
                                            $selected = ($options->_type == 1) ? "selected='selected'" : ""; 
                                        ?>
                                        <option value='1' <?php echo $selected ?>>Before each post</option>
                                        
                                        <?php
                                            $selected = ($options->_type == 2) ? "selected='selected'" : ""; 
                                        ?>
                                        <option value='2' <?php echo $selected ?>>After each post</option>
                                    </select>
                                </abbr></td>
                        </tr>
                       </table>
            </div></div>

            <!--Destination page setup section with it's fields and notes-->
            <div id="heads-up" class="postbox ">
                <h3><span>DESTINATION PAGE SETUP</span></h3>
                <div class="inside">

                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>URL :</b></td>
                            <td class="connatix_in"><?php echo get_site_url() . "/"; ?>
                                <input type="hidden" name="id" value="-1"/>
                            </td>
                            <td><abbr title="Custom permalink.">
                                    <input type="text" name="dest" placeholder = "destpage" maxlength="20" value="<?php echo $options->_dest ?>" /></abbr></td>
                        </tr>
                        <tr>
                            <td colspan="3"><b><span style="color:green;">Current permalink: &nbsp;</b><?php echo get_permalink($options->_id); ?></span></td>
                        </tr>
                    </table></div></div>
        </div>      


        <!--Submit form button-->
        <p class="submit" id="mybutton">
            <input type="submit" class="button-primary" value="Save Changes" />
        </p>
    </form>

    <!--Footer-->
    <br/><br/><hr/><br/><br/>
         <div class="logo"></div>

</div>
<script>
    var CONNATIX_PARTNER_API = "<?php echo CONNATIX_PARTNER_API; ?>?token=";
</script>