<!--The page-->
<div class="wrap">
    <style>
        .connatix-preloader
        {
            width:100%;
            height:100%;
            background:#000000;
            position: absolute;
            top:0px;
            left:0px;
            z-index:100;
            opacity:0.2;
            filter:alpha(opacity=20);
            display:none;
        }
        
        .connatix-preloader img
        {
            margin:80px auto;
            display:block;
        }
        
    </style>
    <div class='connatix-preloader'>
          <img src="<?php echo CONNATIX_PLUGIN_URL . "img/loader.gif"; ?>"/> 
    </div>
    <h2 class="title">
        Connatix Product Bundle - <b>InFeed</b> Integration
    </h2>

    <!-- Beginning of the Plugin Options Form 1 -->
    <form method="post" action="options-general.php?page=<?php echo ConnatixPlugin::$PLUGIN_FILE ?>" id="form1">
        <input type='hidden' name='action' value='<?php echo ConnatixJSPlugin::$POST_ACTION ?>'/>
        <!--General settings section with it's fields and notes-->
        <div id="postlist"><div id="heads-up" class="postbox ">
                <h3><span>GENERAL SETTINGS</span></h3>
                <div class="inside">
                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>PUBLIC TOKEN:</b></td>
                            <td>
                                <abbr title="The public token provided.">
                                <input type="text" maxlength="100" name="token" value="<?php echo $options->_token; ?>" /></abbr></td>
                        </tr>
                        <tr>
                            <td colspan="2"> <span class="description">* Insert the public token provided, here.</span></td>
                        </tr>
                    </table></div></div>

            <!--Listing ad unit section with it's fields and notes-->
            <div id="heads-up" class="postbox ">
                <h3><span>AD UNIT</span></h3>
                <div class="inside">

                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>Page</b></td>
                            <td>
                                <abbr title="The category page you want to install the ad">
                                    <select name="categoryID">
                                        <?php 
                                        $cat_url = get_home_url();
                                        echo "<option value='0' data-link='$cat_url'>Homepage</option>";
                                        
                                        foreach($categories as $category)
                                        {
                                            $category_url = get_category_link($category->cat_ID);
                                           
                                            if($category->cat_ID == $options->_categoryID)
                                            {
                                                $selected = "selected='selected'";
                                                $cat_url = $category_url;
                                            }
                                            
                                            echo "<option data-link='$category_url' $selected value='".$category->cat_ID."'>".$category->name."</option>";
                                        }
                                        ?>
                                    </select>
                                    <a href="<?php echo $cat_url ?>" target="_blank" class="category-page-link">Go to page</a>
                                </abbr>
                            </td>
                        </tr>
                        
                        <tr>
                            <td class="connatix_head"><b>Page Path (jQuery Friendly)</b></td>
                            <td><abbr title="The page you want to install the ad">
                                    <input type="text" name="dom_path" value="<?php echo $options->_dom_path; ?>" /></abbr></td>
                        </tr>
                        
                        <tr>
                            <td class="connatix_head"><b>LISTING POSITION</b></td>
                            <td><abbr title="Position where the ad should be in posts.">
                                <input type="number" name="pos" maxlength="4" value="<?php echo $options->_pos; ?>" /></abbr></td>
                        </tr>
                        <tr>
                            <td colspan="3"> <span class="description">* Insert the listing position for the ad.</span></td>
                        </tr>
                        
                         
                       
                       </table></div></div>

            <!--Destination page setup section with it's fields and notes-->
            <div id="heads-up" class="postbox ">
                <h3><span>DESTINATION PAGE SETUP</span></h3>
                <div class="inside">

                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>PERMANENT LINK:</b></td>
                            <td class="connatix_in"><?php echo get_site_url() . "/"; ?>
                                <input type="hidden" name="id" value="-1"/>
                            </td>
                            <td><abbr title="Custom permalink.">
                                    <input type="text" name="dest" placeholder = "destpage" maxlength="20" value="<?php echo $options->_dest ?>" /></abbr></td>
                        </tr>
                        <tr>
                            <td colspan="3"><b><span style="color:green;">Current permalink: &nbsp;</b><?php echo get_permalink($options->_id); ?></span></td>
                        </tr>
                    </table></div></div>
        </div>      


        <!--Submit form button-->
        <p class="submit" id="mybutton">
            <input type="submit" class="button-primary" value="Save Changes" />
        </p>
    </form>

    <!--Footer-->
    <br/><br/><hr/><br/><br/><img src="<?php echo CONNATIX_PLUGIN_URL . "img/logo.png"; ?>" width="194" height="30" alt="logo" style="display: block; margin-left: auto; margin-right: auto;" />
</div>
<script>
    var CONNATIX_PARTNER_API = "<?php echo CONNATIX_PARTNER_API; ?>?token=";
</script>