<?php
$url_path = "options-general.php?page=". ConnatixPlugin::$PLUGIN_FILE . "&ad_id=";
$home_path = "options-general.php?page=". ConnatixPlugin::$PLUGIN_FILE;

$form_url = ($ad_id != null && $ad_id != -1) ? $url_path . $ad_id : $home_path;
?>

<!--The page-->
<div class="wrap connatix-wrap">
    <div class='connatix-preloader'>
          <img src="<?php echo CONNATIX_PLUGIN_URL . "img/loader.gif"; ?>"/> 
    </div>
    
    <?php
        require_once plugin_dir_path(__FILE__) . "connatix.menu.phtml"; 
    ?>
    <?php
    if($ad_id != null && $ad_id == -1)
    {
       echo "<b>*** Note: Add a new ad or pick an already created one from the right toolbox</b>";
    }
    ?>
    <!-- Beginning of the Plugin Options Form 1 -->
    <form method="post" action="<?php echo $form_url ?>" id="form1">
        <?php if($ad_id != -1) { ?>
            <input type='hidden' name='id' value="<?php echo $ad_id ?>" />
        <?php } ?>
        <input type='hidden' name='action' value='<?php echo ConnatixJSPlugin::$POST_ACTION ?>'/>
          <div id="heads-toolbox" class="connatix-toolbox" id="connatix-toolbox">
              <h3><a class='connatix-add-new' href='<?php echo $home_path ?>'>Add New<span>+</span></a></h3>
                <ul>
                    <?php 
                        foreach($ads as $ad)
                        {
                            $u = $url_path . $ad->_id;
                            $selected = $ad == $ad_unit ? "class='selected'" : "";
                            $name = (isset($ad->_name)) ? $ad->_name : "No Name";
                            
                            echo "<li $selected><a href='$u'>$name</a></li>";
                        }
                    ?>
                </ul>
            </div>
        <!--General settings section with it's fields and notes-->
        <div id="postlist">
          
            <div id="heads-up" class="postbox ">
                <h3><span>GENERAL SETTINGS</span></h3>
                <div class="inside">
                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>AD Unit Name:</b></td>
                            <td>
                                <abbr title="The ad unit name">
                                <input type="text" maxlength="100" name="name" value="<?php echo $ad_unit->_name; ?>" /></abbr></td>
                        </tr>
                        <tr>
                            <td class="connatix_head"><b>PUBLIC TOKEN:</b></td>
                            <td>
                                <abbr title="The public token provided.">
                                <input type="text" maxlength="100" name="token" value="<?php echo $ad_unit->_token; ?>" /></abbr></td>
                        </tr>
                        <tr>
                            <td colspan="2"> <span class="description">* Insert the public token provided, here.</span></td>
                        </tr>
                    </table></div></div>

            <!--Listing ad unit section with it's fields and notes-->
            <div id="heads-up" class="postbox ad-unit">
                <h3><span>AD UNIT</span></h3>
                <div class="inside">

                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>Page</b></td>
                            <td>
                                <abbr title="The category page you want to install the ad">
                                    <select name="categoryID[]" class='connatix-page-selector' multiple="multiple">
                                        <?php 
                                        $cat_url = get_home_url();
                                        
                                        $sel = in_array(0, $ad_unit->_categoryID) ? "selected='selected'" : "";
                                        
                                        echo "<option value='0' data-link='$cat_url' $sel>Homepage</option>";
                                        
                                        $sel = in_array(-1, $ad_unit->_categoryID) ? "selected='selected'" : "";
                                        
                                        echo "<option value='-1' data-link='javascript:void(0)' $sel>All Post Pages</option>";
                                        
                                        foreach($categories as $category)
                                        {
                                            $category_url = get_category_link($category->cat_ID);
                                            $selected = "";
                                            if(in_array($category->cat_ID,$ad_unit->_categoryID))
                                            {
                                                $selected = "selected='selected'";
                                                $cat_url = $category_url;
                                            }
                                            
                                            echo "<option data-link='$category_url' $selected value='".$category->cat_ID."'>".$category->name."</option>";
                                        }
                                        ?>
                                    </select>
                                </abbr>
                            </td>
                        </tr>
                        
                        <tr>
                            <td class="connatix_head"><b>Page Path (jQuery Friendly)</b></td>
                            <td><abbr title="The page you want to install the ad">
                                    <input type="text" name="dom_path" value="<?php echo $ad_unit->_dom_path; ?>" /></abbr></td>
                        </tr>
                        
                        <tr>
                            <td class="connatix_head"><b>LISTING POSITION</b></td>
                            <td><abbr title="Position where the ad should be in posts.">
                                <input type="number" name="pos" maxlength="4" value="<?php echo $ad_unit->_pos; ?>" /></abbr></td>
                        </tr>
                        <tr>
                            <td colspan="3"> <span class="description">* Insert the listing position for the ad.</span></td>
                        </tr>
                        
                        <tr>
                            <?php
                            $selected = ($ad_unit->_skip_adunit) ? "checked='checked'" : "";
                            ?>
                            <td colspan="3"> <span class="description"><input data-ignore='true' type="checkbox" value="1" name="skip_adunit" <?php echo $selected ?>/> <b>* Widget Only</b></span></td>
                        </tr>
                         
                       
                       </table></div></div>

            <!--Destination page setup section with it's fields and notes-->
            <div id="heads-up" class="postbox ">
                <h3><span>DESTINATION PAGE SETUP</span></h3>
                <div class="inside">

                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>PERMANENT LINK:</b></td>
                            <td class="connatix_in"><?php echo get_site_url() . "/"; ?>
                            </td>
                            <td><abbr title="Custom permalink.">
                                    <input type="text" name="dest" placeholder = "destpage" maxlength="20" value="<?php echo $ad_unit->_dest ?>" /></abbr></td>
                        </tr>
                        <tr>
                            <td colspan="3"><b><span style="color:green;">Current permalink: &nbsp;</b><?php echo get_permalink($ad_unit->_id); ?></span></td>
                        </tr>
                    </table></div></div>
        </div>      

        <div class="clear"></div>
        <!--Submit form button-->
        <p class="submit" id="mybutton">
            <input type="submit"  name="delete" class="button-primary connatix-ad-delete" value="Delete ad" />
            <input type="submit" class="button-primary" value="Save Changes" />
        </p>
    </form>

    <!--Footer-->
    <br/><br/><hr/><br/><br/><img src="<?php echo CONNATIX_PLUGIN_URL . "img/logo.png"; ?>" width="194" height="30" alt="logo" style="display: block; margin-left: auto; margin-right: auto;" />
</div>
<script>
    var CONNATIX_PARTNER_API = "<?php echo CONNATIX_PARTNER_API; ?>?token=";
</script>