<!--The page-->
<div class="wrap">
    <h2 class="title">
        Connatix In Feed Plugin v<?php echo CONNATIX_INFEED_VERSION; ?>
    </h2>
    
    

    <!-- Beginning of the Plugin Options Form 1 -->
    <form method="post" action="options.php" id="form1">
        
        <?php
        settings_fields(ConnatixPlugin::$OPTION_GROUP);
        
        ?>
        <!--General settings section with it's fields and notes-->
        <div id="postlist"><div id="heads-up" class="postbox ">
                <h3><span>GENERAL SETTINGS</span></h3>
                <div class="inside">

                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>PUBLIC TOKEN:</b></td>
                            <td>
                                <abbr title="The public token provided.">
                                <input type="text" maxlength="100" name="connatix_options[1][token]" value="<?php echo $options["1"]["token"]; ?>" /></abbr></td>
                        </tr>
                        <tr>
                            <td colspan="2"> <span class="description">* Insert the public token provided, here.</span></td>
                        </tr>
                    </table></div></div>

            <!--Listing ad unit section with it's fields and notes-->
            <div id="heads-up" class="postbox ">
                <h3><span>LISTING AD UNIT</span></h3>
                <div class="inside">

                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>LISTING POSITION</b></td>
                            <td><abbr title="Position where the ad should be in posts."><input type="number" name="connatix_options[1][pos]" maxlength="4" value="<?php echo $options["1"]["pos"]; ?>" /></abbr></td>
                        </tr>
                        <tr>
                            <td colspan="3"> <span class="description">* Insert the listing position for the ad.</span></td>
                        </tr>
                    </table></div></div>

            <!--Destination page setup section with it's fields and notes-->
            <div id="heads-up" class="postbox ">
                <h3><span>DESTINATION PAGE SETUP</span></h3>
                <div class="inside">

                    <table class="form-table">
                        <tr>
                            <td class="connatix_head"><b>PERMANENT LINK:</b></td>
                            <td class="connatix_in"><?php echo get_site_url()."/"; ?><input type="hidden" name="connatix_options[1][id]" value="1"/><input type="hidden" name="connatix_options[1][path]" value="/"/><input type="hidden" name="connatix_options[1][javascript]" value="<?php echo $options[1]["javascript"]; ?>"/><input type="hidden" name="connatix_options[1][path]" value="/"/><input type="hidden" name="connatix_options[1][page_id]" value="<?php echo $options[1]["page_id"]; ?>"/></td>
                            <td><abbr title="Custom permalink."><input type="text" name="connatix_options[1][dest]" placeholder = "destpage" maxlength="20" value="<?php echo $options["1"]["dest"]; ?>" /></abbr></td>
                        </tr>
                        <tr>
                            <td colspan="3"><b><span style="color:green;">Current permalink: &nbsp;</b><?php echo get_permalink($options["1"]["page_id"]); ?></span></td>
                        </tr>
                        <tr>
                            <td colspan="3"> <span class="description">* Insert the destination page name (or let the default value: "promoted"). Be sure that in Settings -> General, the fields "WordPress Address (URL)" and "Site Address (URL)" are not empty.</span></td>
                        </tr>
                    </table></div></div>
        </div>      


        <!--Submit form button-->
        <p class="submit" id="mybutton">
            <input type="submit" class="button-primary" value="Save Changes" />
            <input type="button" class="button-primary" id="connatix-advanced" style="float: right" value="Show Advanced Setup" />
        </p>
    </form>
    <!--End first form-->
        
    <!--Advanced settings section (expandable) with it's fields and notes-->
        
    <!--Second form-->    
    <form method="post" action="options.php" id="form2">  
   
       <?php
        settings_fields(ConnatixPlugin::$OPTION_GROUP);
        ?>
            <div id="postlist"><div  id="heads-up" class="postbox">
            <h3><span>AD MANAGEMENT</span></h3>
            <div class="inside">

        <table id="connatix_ad_management" class="form-table" border="1" style="border:1px solid #eee ">        
            <!--Table header-->
            <tr>
                <th>AD URL Pattern</th>
                <th>AD Token</th>
                <th>Destination Page</th>
                <th>Listing Position</th> 
                <th>Action</th>
                
            </tr>    
            <!--Adding data to the HTML table-->
            <?php
            $advanced = false;
            if($options!= null){
                $k = 0;$advanced = false;
                foreach ($options as $row) {
                
                           
            ?>    
            <tr>
                <td><input type="hidden" name="connatix_options[<?php echo $row['id']; ?>][path]" value="<?php echo $row['path']; ?>"/><?php echo $row['path']; ?></td>
                <td><input type="hidden" name="connatix_options[<?php echo $row['id']; ?>][token]" value="<?php echo $row['token']; ?>"/><?php echo $row['token']; ?></td>
                <td><input type="hidden" name="connatix_options[<?php echo $row['id']; ?>][dest]" value="<?php echo $row['dest']; ?>"/><?php echo $row['dest']; ?></td>
                <td><input type="hidden" name="connatix_options[<?php echo $row['id']; ?>][pos]" value="<?php echo $row['pos']; ?>"/><?php echo $row['pos']; ?>
                    <input type="hidden" name="connatix_options[<?php echo $row['id']; ?>][page_id]" value="<?php echo $row['page_id']; ?>"/>                     </td>
                <td><input type="hidden" name="connatix_options[<?php echo $row['id']; ?>][id]" value="<?php echo $row['id']; ?>"/><input type="button" style="width: 130px !important;" onclick="connatix_remove_line()" class="button-primary" value="Delete" /></td>
            </tr>
            <?php
                $k++;
                }
                if($k>1){    
                $advanced = true;
                }
            }    
            ?>    
            <!--Basic input fields for the table-->
            <tr>
                <td><abbr title='Enter the name of the page you want your ad to be on. " / " is for homepage, you can put multiple strings separated by: " , "'><input type="text" maxlength="100" id="path" value="" /></abbr></td>
                <td><abbr title="The public token provided."><input type="text" id="token" maxlength="100" value="" /></abbr></td>
                <td><span style="float: left;font-size: 22px;font-weight: 100;">.../</span><abbr title="Destination page name."><input type="text" id="dest" placeholder = "destpage" maxlength="20" value="" /></abbr></td>
                <td><abbr title="Position where the ad should be in posts."><input type="number" id="pos" value="" style="width:130px" maxlength="4" /></abbr></td>
                <td><input type="button" style="width: 130px !important;" id="connatix_add_values" class="button-primary" value="Add entry" /></td>
            </tr>
        </table></div></div>
            
            <!--Javascript textarea section-->
            <div id="heads-up" class="postbox">
            <h3><span>JAVASCRIPT</span></h3>
            <div class="inside">
                
        <table class="form-table" >
                <tr>
                    <td><b>Javascript code:</b><abbr title = "Here you can add your own javascript for responsiveness or other things." ><textarea name="connatix_options[1][javascript]" rows="5" cols="40" type='textarea'><?php echo $options["1"]["javascript"]; ?></textarea><br /></abbr></td>
                </tr>
                <tr>
                   <td> <span class="description">* The javascript in this box will pe applied to the ad. Use ' not " .</span></td>
                </tr>
        </table></div></div></div>
            
            <p class="submit" id="mybutton">
                <input type="submit" class="button-primary" value="Save Changes" />
                <input type="button" class="button-primary" id="connatix-advanced2" style="float: right" value="Hide Advanced Setup" />
            </p>
    </form>
    <!--End second form-->
    <!--Footer-->
    <br/><br/><hr/><br/><br/><img src="<?php echo CONNATIX_PLUGIN_URL . "img/logo.png"; ?>" width="194" height="30" alt="logo" style="display: block; margin-left: auto; margin-right: auto;" />
</div>
 <!--The javascript for advanced section hide functions + buttons-->
        <script>
            $(document).ready(function(){
                  <?php  if ($advanced==false){ ?>
                  page1();        
                  <?php  }else{ ?>
                  page2();
                  <?php  } ?>
                  $("#connatix-advanced").click(hidesection);
                  $("#connatix-advanced2").click(hidesection);
                  $("#connatix_add_values").click(connatix_add_values);  
            });
            
        </script>
        