<!--The page-->
<div class="wrap connatix-wrap">
    <div class='connatix-preloader'>
        <img src="<?php echo CONNATIX_PLUGIN_URL . "img/loader.gif"; ?>"/> 
    </div>

    <?php
    require_once plugin_dir_path(__FILE__) . "connatix.menu.phtml";
    ?>

    <div style="padding: 10% 20% 10% 20%;">
        <h1 style="text-align: center;">
            This product was removed.
        </h1>
        <h3 style="text-align: center;padding-top: 20px;">Please return to INFEED</h3>
    </div>
    <!--Footer-->
    <span id="connatix-support" class="alignright">For any questions contact us at: support@connatix.com</span>
    <hr class="connatix-break"/>
    <div class="logo"></div>

</div>
